# Form implementation generated from reading ui file 'app/ui/qt/about_developer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDeveloper(object):
    def setupUi(self, AboutDeveloper):
        AboutDeveloper.setObjectName("AboutDeveloper")
        AboutDeveloper.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        AboutDeveloper.resize(340, 250)
        AboutDeveloper.setMinimumSize(QtCore.QSize(340, 250))
        AboutDeveloper.setMaximumSize(QtCore.QSize(340, 250))
        AboutDeveloper.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Russia))
        AboutDeveloper.setSizeGripEnabled(False)
        AboutDeveloper.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(AboutDeveloper)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=AboutDeveloper)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 35))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    background: rgb(99, 230, 200);\n"
"    border-radius: 10%;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"        background: rgba(99, 230, 200, 0.5);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=AboutDeveloper)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=AboutDeveloper)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=AboutDeveloper)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=AboutDeveloper)
        self.label_2.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 5, 0, 1, 1)

        self.retranslateUi(AboutDeveloper)
        QtCore.QMetaObject.connectSlotsByName(AboutDeveloper)

    def retranslateUi(self, AboutDeveloper):
        _translate = QtCore.QCoreApplication.translate
        AboutDeveloper.setWindowTitle(_translate("AboutDeveloper", "О разработчике"))
        self.pushButton.setText(_translate("AboutDeveloper", "Закрыть"))
        self.label.setText(_translate("AboutDeveloper", "Разработчик:"))
        self.label_4.setText(_translate("AboutDeveloper", "<html><head/><body><p><a href=\"https://linktr.ee/immmax\"><span style=\" text-decoration: underline; color:#3586ff;\">LinkTree</span></a></p></body></html>"))
        self.label_3.setText(_translate("AboutDeveloper", "Максим Дацкий"))
        self.label_2.setText(_translate("AboutDeveloper", "Как связаться:"))
