# Form implementation generated from reading ui file 'app/ui/qt/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_launch_view = QtWidgets.QWidget()
        self.page_launch_view.setObjectName("page_launch_view")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_launch_view)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(17, 56, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_app_title = QtWidgets.QLabel(parent=self.page_launch_view)
        self.label_app_title.setMinimumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_app_title.setFont(font)
        self.label_app_title.setStyleSheet("QLabel {\n"
"    padding: 5px;\n"
"    border: 3px solid pink;\n"
"    border-radius: 20%;\n"
"}")
        self.label_app_title.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Russia))
        self.label_app_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_app_title.setWordWrap(False)
        self.label_app_title.setObjectName("label_app_title")
        self.horizontalLayout_2.addWidget(self.label_app_title)
        spacerItem2 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(17, 58, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_description = QtWidgets.QLabel(parent=self.page_launch_view)
        self.label_description.setMinimumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_description.setFont(font)
        self.label_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout_3.addWidget(self.label_description)
        spacerItem5 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(17, 57, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_current_version = QtWidgets.QLabel(parent=self.page_launch_view)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        self.label_current_version.setFont(font)
        self.label_current_version.setObjectName("label_current_version")
        self.horizontalLayout_5.addWidget(self.label_current_version)
        self.label_version_number = QtWidgets.QLabel(parent=self.page_launch_view)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.label_version_number.setFont(font)
        self.label_version_number.setObjectName("label_version_number")
        self.horizontalLayout_5.addWidget(self.label_version_number)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.pushButton_go_to_edit = QtWidgets.QPushButton(parent=self.page_launch_view)
        self.pushButton_go_to_edit.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_go_to_edit.setMaximumSize(QtCore.QSize(60, 300))
        self.pushButton_go_to_edit.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    background: rgb(99, 230, 200);\n"
"    border-radius: 10%;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"        background: rgba(99, 230, 200, 0.5);\n"
"}")
        self.pushButton_go_to_edit.setObjectName("pushButton_go_to_edit")
        self.horizontalLayout.addWidget(self.pushButton_go_to_edit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(17, 56, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.pushButton_about_developer = QtWidgets.QPushButton(parent=self.page_launch_view)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.pushButton_about_developer.setFont(font)
        self.pushButton_about_developer.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"}")
        self.pushButton_about_developer.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Russia))
        self.pushButton_about_developer.setObjectName("pushButton_about_developer")
        self.horizontalLayout_4.addWidget(self.pushButton_about_developer)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_launch_view)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Fellowship Editor"))
        self.label_app_title.setText(_translate("MainWindow", "Home Fellowship Editor"))
        self.label_description.setText(_translate("MainWindow", "Данная программа предназначена для редактирования JSON-файла, содержащего данные для iOS-приложения\n"
"\n"
"HOME FELLOWSHIP"))
        self.label_current_version.setText(_translate("MainWindow", "Текущая версия приложения:"))
        self.label_version_number.setText(_translate("MainWindow", "v0.0"))
        self.pushButton_go_to_edit.setText(_translate("MainWindow", "Редактировать"))
        self.pushButton_about_developer.setText(_translate("MainWindow", "2023 © Maxim Datskiy"))
